// Code generated - DO NOT EDIT.
// This file is a generated protobuf definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: connectors/source/traderjoe/joefactory/joefactory.gen.proto

package joefactory

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PairCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Token0 []byte                 `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1 []byte                 `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty"`
	Pair   []byte                 `protobuf:"bytes,4,opt,name=pair,proto3" json:"pair,omitempty"`
	Arg3   []byte                 `protobuf:"bytes,5,opt,name=arg3,proto3" json:"arg3,omitempty"` // uint256
}

func (x *PairCreated) Reset() {
	*x = PairCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairCreated) ProtoMessage() {}

func (x *PairCreated) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairCreated.ProtoReflect.Descriptor instead.
func (*PairCreated) Descriptor() ([]byte, []int) {
	return file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescGZIP(), []int{0}
}

func (x *PairCreated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *PairCreated) GetToken0() []byte {
	if x != nil {
		return x.Token0
	}
	return nil
}

func (x *PairCreated) GetToken1() []byte {
	if x != nil {
		return x.Token1
	}
	return nil
}

func (x *PairCreated) GetPair() []byte {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *PairCreated) GetArg3() []byte {
	if x != nil {
		return x.Arg3
	}
	return nil
}

var File_connectors_source_traderjoe_joefactory_joefactory_gen_proto protoreflect.FileDescriptor

var file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x6a, 0x6f, 0x65, 0x2f, 0x6a, 0x6f,
	0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x6a, 0x6f, 0x65, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6a,
	0x6f, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x50,
	0x61, 0x69, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x67, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x33, 0x42, 0x24,
	0x5a, 0x22, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6a, 0x6f, 0x65, 0x66, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescOnce sync.Once
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescData = file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDesc
)

func file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescGZIP() []byte {
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescOnce.Do(func() {
		file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescData)
	})
	return file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDescData
}

var file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_goTypes = []interface{}{
	(*PairCreated)(nil),           // 0: joefactory.PairCreated
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_depIdxs = []int32{
	1, // 0: joefactory.PairCreated.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_init() }
func file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_init() {
	if File_connectors_source_traderjoe_joefactory_joefactory_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_goTypes,
		DependencyIndexes: file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_depIdxs,
		MessageInfos:      file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_msgTypes,
	}.Build()
	File_connectors_source_traderjoe_joefactory_joefactory_gen_proto = out.File
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_rawDesc = nil
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_goTypes = nil
	file_connectors_source_traderjoe_joefactory_joefactory_gen_proto_depIdxs = nil
}
