// Code generated by connectorgen.
// go run ./connectors/source/opensea/cmd/opensea_backfill/main.go --fromBlock 11945500 --toBlock 11945502
package main

import (
	"context"
	"encoding/json"
	"math/big"
	"net/http"
	"net/url"
	"time"

	"blep.ai/data/chain/ethereum/ethclient"
	"blep.ai/data/config"
	"blep.ai/data/connectors/source/opensea"
	"blep.ai/data/database"
	"github.com/nakji-network/connector/kafkautils"

	_ "net/http/pprof"

	geth "github.com/ethereum/go-ethereum"
	ethcommon "github.com/ethereum/go-ethereum/common"
	ethtypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/rs/zerolog/log"
	"github.com/spf13/pflag"
)

type Status struct {
	Step            int
	EventsProcessed map[string]uint64
	CurrentBlock    uint64
	Errors          []error
	FromBlock       int64
	ToBlock         int64
}

func main() {
	// Memory profiling
	go http.ListenAndServe(":6060", nil)

	// Load config in here to support flags
	pflag.Int64("fromBlock", 10000835, "backfill from this block")
	pflag.Int64("toBlock", 12000000, "backfill to this block")
	pflag.Int64("blockChunk", 3000, "get 100 blocks at a time to prevent timeouts")
	pflag.Int64P("maxConnections", "c", 10, "max simultaneous connections")
	pflag.Bool("upsert", true, "uses batch instead of COPY FROM when existing entries might exist")
	pflag.Int("dbBatch", 3000, "batch db writes by x items")
	pflag.Int64("processPairConcurrency", 4096, "max goroutines for pairProcessLog")

	var conf = config.InitConfig()

	conf.SetDefault("opensea.wyvernexchangev1Address", "0x7Be8076f4EA4A4AD08075C2508e481d6C946D12b")
	conf.SetDefault("opensea.wyvernexchangev2Address", "0x7f268357A8c2552623316e2562D90e642bB538E5")

	// get status of this long running status
	status := Status{
		FromBlock: conf.GetInt64("fromBlock"),
		ToBlock:   conf.GetInt64("toBlock"),
	}
	http.HandleFunc("/status", func(w http.ResponseWriter, req *http.Request) {
		js, err := json.Marshal(status)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write(js)
	})
	go http.ListenAndServe(":8080", nil)

	// Load Topic registry
	kafkautils.TopicTypeRegistry.Load(opensea.TopicTypes)

	rpcUrls := []string{(&url.URL{
		Scheme: conf.GetString("ethereum.archival.scheme"),
		User:   url.UserPassword(conf.GetString("ethereum.archival.username"), conf.GetString("ethereum.archival.password")),
		Host:   conf.GetString("ethereum.archival.host"),
		Path:   conf.GetString("ethereum.archival.path"),
	}).String(),
		(&url.URL{ // hacky to get past wss error
			Scheme: "wss",
			User:   url.UserPassword(conf.GetString("ethereum.archival.username"), conf.GetString("ethereum.archival.password")),
			Host:   conf.GetString("ethereum.archival.host"),
			Path:   conf.GetString("ethereum.archival.path"),
		}).String()}

	ethClientPool, err := ethclient.DialPoolContext(context.Background(), rpcUrls)
	if err != nil {
		log.Fatal().Err(err).Msg("Ethereum RPC connection error")
	}

	// Init historical db
	db, err := database.New(conf.GetString("timescaledb.connection"))
	if err != nil {
		log.Fatal().Err(err).Str("dsn", conf.GetString("timescaledb.connection")).Msg("Timescaledb connection failed")
	}
	defer db.Close()

	wyvernexchangev1Address := ethcommon.HexToAddress(conf.GetString("opensea.wyvernexchangev1Address"))
	wyvernexchangev2Address := ethcommon.HexToAddress(conf.GetString("opensea.wyvernexchangev2Address"))

	addresses := []ethcommon.Address{
		wyvernexchangev1Address,
		wyvernexchangev2Address,
	}

	query := geth.FilterQuery{
		Addresses: addresses,
		FromBlock: big.NewInt(conf.GetInt64("fromBlock")),
		ToBlock:   big.NewInt(conf.GetInt64("toBlock")),
	}

	client, err := ethClientPool.RandClient(true)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to find available client")
	}

	logsChan, _ := client.ChunkedFilterLogs(query, 0, conf.GetInt64("blockChunk"), conf.GetInt64("maxConnections"))

	start := time.Now()

	topics := map[string]kafkautils.Topic{
		"wyvernexchangev1_orderapprovedpartone": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_orderapprovedpartone"), conf.GetString("kafka.env")),
		"wyvernexchangev1_orderapprovedparttwo": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_orderapprovedparttwo"), conf.GetString("kafka.env")),
		"wyvernexchangev1_ordercancelled":       kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_ordercancelled"), conf.GetString("kafka.env")),
		"wyvernexchangev1_ordersmatched":        kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_ordersmatched"), conf.GetString("kafka.env")),
		"wyvernexchangev1_ownershiprenounced":   kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_ownershiprenounced"), conf.GetString("kafka.env")),
		"wyvernexchangev1_ownershiptransferred": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev1_ownershiptransferred"), conf.GetString("kafka.env")),
		"wyvernexchangev2_nonceincremented":     kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_nonceincremented"), conf.GetString("kafka.env")),
		"wyvernexchangev2_orderapprovedpartone": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_orderapprovedpartone"), conf.GetString("kafka.env")),
		"wyvernexchangev2_orderapprovedparttwo": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_orderapprovedparttwo"), conf.GetString("kafka.env")),
		"wyvernexchangev2_ordercancelled":       kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_ordercancelled"), conf.GetString("kafka.env")),
		"wyvernexchangev2_ordersmatched":        kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_ordersmatched"), conf.GetString("kafka.env")),
		"wyvernexchangev2_ownershiprenounced":   kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_ownershiprenounced"), conf.GetString("kafka.env")),
		"wyvernexchangev2_ownershiptransferred": kafkautils.MustParseTopic(conf.GetString("opensea.kafka.topic.wyvernexchangev2_ownershiptransferred"), conf.GetString("kafka.env")),
	}

	connector := opensea.OpenseaConnector{
		Topics: topics,
	}

	// database write buffer
	buffer := make([]*kafkautils.Message, 0, conf.GetInt("dbBatch"))

	logToMessage := map[string]func(ethtypes.Log) *kafkautils.Message{
		conf.GetString("opensea.wyvernexchangev1Address"): connector.Wyvernexchangev1LogToMsg,
		conf.GetString("opensea.wyvernexchangev2Address"): connector.Wyvernexchangev2LogToMsg,
	}

	for evLog := range logsChan {
		status.CurrentBlock = evLog.BlockNumber
		msg := logToMessage[evLog.Address.Hex()](evLog)
		status.EventsProcessed[msg.Topic.Schema()]++

		buffer = append(buffer, msg)

		// Flush to db
		if len(buffer) == conf.GetInt("dbBatch") {
			if conf.GetBool("upsert") {
				errs := db.InsertBatchKafkaMessages(buffer)
				for _, err := range errs {
					log.Error().Err(err).
						Msg("InsertBatchKafkaMessages error")
					status.Errors = append(status.Errors, err)
				}
			} else {
				err = db.CopyFromKafkaMessages(context.Background(), "nakji.common.0_0_0.liquiditypool_change", buffer)
				if err != nil {
					log.Error().Err(err).
						Msg("CopyFromKafkaMessages error")
					status.Errors = append(status.Errors, err)
				}
			}

			log.Info().
				Dur("time", time.Since(start)).
				Interface("lastmsg", msg).
				//Interface("status", status).
				Msg("opensea backfill in progress")

			buffer = nil
		}
	}

	// Flush remaining buffer
	if conf.GetBool("upsert") {
		errs := db.InsertBatchKafkaMessages(buffer)
		for _, err := range errs {
			log.Error().Err(err).
				Msg("InsertBatchKafkaMessages error")
			status.Errors = append(status.Errors, err)
		}
	} else {
		err = db.CopyFromKafkaMessages(context.Background(), "nakji.common.0_0_0.liquiditypool_change", buffer)
		if err != nil {
			log.Error().Err(err).
				Msg("CopyFromKafkaMessages error")
			status.Errors = append(status.Errors, err)
		}
	}

	log.Info().
		Dur("totaltime", time.Since(start)).
		Interface("status", &status).
		Msg("opensea backfill completed")
}
