// Code generated - DO NOT EDIT.
// This file is a generated protobuf definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: connectors/source/opensea/wyvernexchangev2/wyvernexchangev2.gen.proto

package wyvernexchangev2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderApprovedPartOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts               *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Hash             []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Exchange         []byte                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Maker            []byte                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Taker            []byte                 `protobuf:"bytes,5,opt,name=taker,proto3" json:"taker,omitempty"`
	MakerRelayerFee  []byte                 `protobuf:"bytes,6,opt,name=makerRelayerFee,proto3" json:"makerRelayerFee,omitempty"`   // uint256
	TakerRelayerFee  []byte                 `protobuf:"bytes,7,opt,name=takerRelayerFee,proto3" json:"takerRelayerFee,omitempty"`   // uint256
	MakerProtocolFee []byte                 `protobuf:"bytes,8,opt,name=makerProtocolFee,proto3" json:"makerProtocolFee,omitempty"` // uint256
	TakerProtocolFee []byte                 `protobuf:"bytes,9,opt,name=takerProtocolFee,proto3" json:"takerProtocolFee,omitempty"` // uint256
	FeeRecipient     []byte                 `protobuf:"bytes,10,opt,name=feeRecipient,proto3" json:"feeRecipient,omitempty"`
	FeeMethod        uint32                 `protobuf:"varint,11,opt,name=feeMethod,proto3" json:"feeMethod,omitempty"`
	Side             uint32                 `protobuf:"varint,12,opt,name=side,proto3" json:"side,omitempty"`
	SaleKind         uint32                 `protobuf:"varint,13,opt,name=saleKind,proto3" json:"saleKind,omitempty"`
	Target           []byte                 `protobuf:"bytes,14,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *OrderApprovedPartOne) Reset() {
	*x = OrderApprovedPartOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderApprovedPartOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderApprovedPartOne) ProtoMessage() {}

func (x *OrderApprovedPartOne) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderApprovedPartOne.ProtoReflect.Descriptor instead.
func (*OrderApprovedPartOne) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{0}
}

func (x *OrderApprovedPartOne) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OrderApprovedPartOne) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *OrderApprovedPartOne) GetExchange() []byte {
	if x != nil {
		return x.Exchange
	}
	return nil
}

func (x *OrderApprovedPartOne) GetMaker() []byte {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *OrderApprovedPartOne) GetTaker() []byte {
	if x != nil {
		return x.Taker
	}
	return nil
}

func (x *OrderApprovedPartOne) GetMakerRelayerFee() []byte {
	if x != nil {
		return x.MakerRelayerFee
	}
	return nil
}

func (x *OrderApprovedPartOne) GetTakerRelayerFee() []byte {
	if x != nil {
		return x.TakerRelayerFee
	}
	return nil
}

func (x *OrderApprovedPartOne) GetMakerProtocolFee() []byte {
	if x != nil {
		return x.MakerProtocolFee
	}
	return nil
}

func (x *OrderApprovedPartOne) GetTakerProtocolFee() []byte {
	if x != nil {
		return x.TakerProtocolFee
	}
	return nil
}

func (x *OrderApprovedPartOne) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *OrderApprovedPartOne) GetFeeMethod() uint32 {
	if x != nil {
		return x.FeeMethod
	}
	return 0
}

func (x *OrderApprovedPartOne) GetSide() uint32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *OrderApprovedPartOne) GetSaleKind() uint32 {
	if x != nil {
		return x.SaleKind
	}
	return 0
}

func (x *OrderApprovedPartOne) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

type OrderApprovedPartTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts                        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Hash                      []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	HowToCall                 uint32                 `protobuf:"varint,3,opt,name=howToCall,proto3" json:"howToCall,omitempty"`
	Calldata                  []byte                 `protobuf:"bytes,4,opt,name=calldata,proto3" json:"calldata,omitempty"`
	ReplacementPattern        []byte                 `protobuf:"bytes,5,opt,name=replacementPattern,proto3" json:"replacementPattern,omitempty"`
	StaticTarget              []byte                 `protobuf:"bytes,6,opt,name=staticTarget,proto3" json:"staticTarget,omitempty"`
	StaticExtradata           []byte                 `protobuf:"bytes,7,opt,name=staticExtradata,proto3" json:"staticExtradata,omitempty"`
	PaymentToken              []byte                 `protobuf:"bytes,8,opt,name=paymentToken,proto3" json:"paymentToken,omitempty"`
	BasePrice                 []byte                 `protobuf:"bytes,9,opt,name=basePrice,proto3" json:"basePrice,omitempty"`            // uint256
	Extra                     []byte                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`                   // uint256
	ListingTime               []byte                 `protobuf:"bytes,11,opt,name=listingTime,proto3" json:"listingTime,omitempty"`       // uint256
	ExpirationTime            []byte                 `protobuf:"bytes,12,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"` // uint256
	Salt                      []byte                 `protobuf:"bytes,13,opt,name=salt,proto3" json:"salt,omitempty"`                     // uint256
	OrderbookInclusionDesired bool                   `protobuf:"varint,14,opt,name=orderbookInclusionDesired,proto3" json:"orderbookInclusionDesired,omitempty"`
}

func (x *OrderApprovedPartTwo) Reset() {
	*x = OrderApprovedPartTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderApprovedPartTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderApprovedPartTwo) ProtoMessage() {}

func (x *OrderApprovedPartTwo) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderApprovedPartTwo.ProtoReflect.Descriptor instead.
func (*OrderApprovedPartTwo) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{1}
}

func (x *OrderApprovedPartTwo) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetHowToCall() uint32 {
	if x != nil {
		return x.HowToCall
	}
	return 0
}

func (x *OrderApprovedPartTwo) GetCalldata() []byte {
	if x != nil {
		return x.Calldata
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetReplacementPattern() []byte {
	if x != nil {
		return x.ReplacementPattern
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetStaticTarget() []byte {
	if x != nil {
		return x.StaticTarget
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetStaticExtradata() []byte {
	if x != nil {
		return x.StaticExtradata
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetPaymentToken() []byte {
	if x != nil {
		return x.PaymentToken
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetBasePrice() []byte {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetListingTime() []byte {
	if x != nil {
		return x.ListingTime
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetExpirationTime() []byte {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *OrderApprovedPartTwo) GetOrderbookInclusionDesired() bool {
	if x != nil {
		return x.OrderbookInclusionDesired
	}
	return false
}

type OrderCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Hash []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *OrderCancelled) Reset() {
	*x = OrderCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelled) ProtoMessage() {}

func (x *OrderCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelled.ProtoReflect.Descriptor instead.
func (*OrderCancelled) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCancelled) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OrderCancelled) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type OrdersMatched struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BuyHash  []byte                 `protobuf:"bytes,2,opt,name=buyHash,proto3" json:"buyHash,omitempty"`
	SellHash []byte                 `protobuf:"bytes,3,opt,name=sellHash,proto3" json:"sellHash,omitempty"`
	Maker    []byte                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Taker    []byte                 `protobuf:"bytes,5,opt,name=taker,proto3" json:"taker,omitempty"`
	Price    []byte                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"` // uint256
	Metadata []byte                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *OrdersMatched) Reset() {
	*x = OrdersMatched{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdersMatched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersMatched) ProtoMessage() {}

func (x *OrdersMatched) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersMatched.ProtoReflect.Descriptor instead.
func (*OrdersMatched) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{3}
}

func (x *OrdersMatched) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OrdersMatched) GetBuyHash() []byte {
	if x != nil {
		return x.BuyHash
	}
	return nil
}

func (x *OrdersMatched) GetSellHash() []byte {
	if x != nil {
		return x.SellHash
	}
	return nil
}

func (x *OrdersMatched) GetMaker() []byte {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *OrdersMatched) GetTaker() []byte {
	if x != nil {
		return x.Taker
	}
	return nil
}

func (x *OrdersMatched) GetPrice() []byte {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrdersMatched) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NonceIncremented struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Maker    []byte                 `protobuf:"bytes,2,opt,name=maker,proto3" json:"maker,omitempty"`
	NewNonce []byte                 `protobuf:"bytes,3,opt,name=newNonce,proto3" json:"newNonce,omitempty"` // uint256
}

func (x *NonceIncremented) Reset() {
	*x = NonceIncremented{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonceIncremented) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceIncremented) ProtoMessage() {}

func (x *NonceIncremented) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceIncremented.ProtoReflect.Descriptor instead.
func (*NonceIncremented) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{4}
}

func (x *NonceIncremented) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *NonceIncremented) GetMaker() []byte {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *NonceIncremented) GetNewNonce() []byte {
	if x != nil {
		return x.NewNonce
	}
	return nil
}

type OwnershipRenounced struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	PreviousOwner []byte                 `protobuf:"bytes,2,opt,name=previousOwner,proto3" json:"previousOwner,omitempty"`
}

func (x *OwnershipRenounced) Reset() {
	*x = OwnershipRenounced{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnershipRenounced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipRenounced) ProtoMessage() {}

func (x *OwnershipRenounced) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipRenounced.ProtoReflect.Descriptor instead.
func (*OwnershipRenounced) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{5}
}

func (x *OwnershipRenounced) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OwnershipRenounced) GetPreviousOwner() []byte {
	if x != nil {
		return x.PreviousOwner
	}
	return nil
}

type OwnershipTransferred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	PreviousOwner []byte                 `protobuf:"bytes,2,opt,name=previousOwner,proto3" json:"previousOwner,omitempty"`
	NewOwner      []byte                 `protobuf:"bytes,3,opt,name=newOwner,proto3" json:"newOwner,omitempty"`
}

func (x *OwnershipTransferred) Reset() {
	*x = OwnershipTransferred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnershipTransferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipTransferred) ProtoMessage() {}

func (x *OwnershipTransferred) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipTransferred.ProtoReflect.Descriptor instead.
func (*OwnershipTransferred) Descriptor() ([]byte, []int) {
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP(), []int{6}
}

func (x *OwnershipTransferred) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OwnershipTransferred) GetPreviousOwner() []byte {
	if x != nil {
		return x.PreviousOwner
	}
	return nil
}

func (x *OwnershipTransferred) GetNewOwner() []byte {
	if x != nil {
		return x.NewOwner
	}
	return nil
}

var File_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto protoreflect.FileDescriptor

var file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDesc = []byte{
	0x0a, 0x45, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x61, 0x2f, 0x77, 0x79, 0x76, 0x65,
	0x72, 0x6e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x76, 0x32, 0x2f, 0x77, 0x79, 0x76,
	0x65, 0x72, 0x6e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x76, 0x32, 0x2e, 0x67, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x77, 0x79, 0x76, 0x65, 0x72, 0x6e, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x76, 0x32, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x03, 0x0a, 0x14, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x4f, 0x6e, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x6d,
	0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x46, 0x65, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f,
	0x74, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x65, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x46, 0x65, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x46, 0x65, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x74,
	0x61, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x46, 0x65, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x46, 0x65, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x66,
	0x65, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x65, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x66, 0x65, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x61, 0x6c, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x73, 0x61, 0x6c, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x82, 0x04, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x54, 0x77, 0x6f, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x6f,
	0x77, 0x54, 0x6f, 0x43, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68,
	0x6f, 0x77, 0x54, 0x6f, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x12, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x45, 0x78, 0x74, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x45, 0x78, 0x74, 0x72, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x19, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x19, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x22, 0x50, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x75, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x10, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x2a,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x66, 0x0a, 0x12,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x24,
	0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x22, 0x84, 0x01, 0x0a, 0x14, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x42, 0x2a, 0x5a, 0x28, 0x62,
	0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x77, 0x79, 0x76, 0x65, 0x72, 0x6e, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescOnce sync.Once
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescData = file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDesc
)

func file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescGZIP() []byte {
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescOnce.Do(func() {
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescData)
	})
	return file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDescData
}

var file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_goTypes = []interface{}{
	(*OrderApprovedPartOne)(nil),  // 0: wyvernexchangev2.OrderApprovedPartOne
	(*OrderApprovedPartTwo)(nil),  // 1: wyvernexchangev2.OrderApprovedPartTwo
	(*OrderCancelled)(nil),        // 2: wyvernexchangev2.OrderCancelled
	(*OrdersMatched)(nil),         // 3: wyvernexchangev2.OrdersMatched
	(*NonceIncremented)(nil),      // 4: wyvernexchangev2.NonceIncremented
	(*OwnershipRenounced)(nil),    // 5: wyvernexchangev2.OwnershipRenounced
	(*OwnershipTransferred)(nil),  // 6: wyvernexchangev2.OwnershipTransferred
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_depIdxs = []int32{
	7, // 0: wyvernexchangev2.OrderApprovedPartOne.ts:type_name -> google.protobuf.Timestamp
	7, // 1: wyvernexchangev2.OrderApprovedPartTwo.ts:type_name -> google.protobuf.Timestamp
	7, // 2: wyvernexchangev2.OrderCancelled.ts:type_name -> google.protobuf.Timestamp
	7, // 3: wyvernexchangev2.OrdersMatched.ts:type_name -> google.protobuf.Timestamp
	7, // 4: wyvernexchangev2.NonceIncremented.ts:type_name -> google.protobuf.Timestamp
	7, // 5: wyvernexchangev2.OwnershipRenounced.ts:type_name -> google.protobuf.Timestamp
	7, // 6: wyvernexchangev2.OwnershipTransferred.ts:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_init() }
func file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_init() {
	if File_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderApprovedPartOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderApprovedPartTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdersMatched); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonceIncremented); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnershipRenounced); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnershipTransferred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_goTypes,
		DependencyIndexes: file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_depIdxs,
		MessageInfos:      file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_msgTypes,
	}.Build()
	File_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto = out.File
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_rawDesc = nil
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_goTypes = nil
	file_connectors_source_opensea_wyvernexchangev2_wyvernexchangev2_gen_proto_depIdxs = nil
}
