// Code generated by connectorgen - Edit as necessary.
package traderjoe

import (
	"blep.ai/data/connectors/source/traderjoe/joebar"
	"blep.ai/data/connectors/source/traderjoe/joefactory"
	"blep.ai/data/connectors/source/traderjoe/joehattoken"
	"blep.ai/data/connectors/source/traderjoe/joepair"
	"blep.ai/data/connectors/source/traderjoe/joetoken"
	"blep.ai/data/connectors/source/traderjoe/joetroller"
	"blep.ai/data/connectors/source/traderjoe/masterchefjoev2"
	"blep.ai/data/connectors/source/traderjoe/masterchefjoev3"
	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]proto.Message{
	"nakji.traderjoe.0_0_0.joebar_approval":                      &joebar.Approval{},
	"nakji.traderjoe.0_0_0.joebar_transfer":                      &joebar.Transfer{},
	"nakji.traderjoe.0_0_0.joefactory_paircreated":               &joefactory.PairCreated{},
	"nakji.traderjoe.0_0_0.joehattoken_approval":                 &joehattoken.Approval{},
	"nakji.traderjoe.0_0_0.joehattoken_transfer":                 &joehattoken.Transfer{},
	"nakji.traderjoe.0_0_0.joepair_approval":                     &joepair.Approval{},
	"nakji.traderjoe.0_0_0.joepair_burn":                         &joepair.Burn{},
	"nakji.traderjoe.0_0_0.joepair_mint":                         &joepair.Mint{},
	"nakji.traderjoe.0_0_0.joepair_swap":                         &joepair.Swap{},
	"nakji.traderjoe.0_0_0.joepair_sync":                         &joepair.Sync{},
	"nakji.traderjoe.0_0_0.joepair_transfer":                     &joepair.Transfer{},
	"nakji.traderjoe.0_0_0.joetoken_approval":                    &joetoken.Approval{},
	"nakji.traderjoe.0_0_0.joetoken_delegatechanged":             &joetoken.DelegateChanged{},
	"nakji.traderjoe.0_0_0.joetoken_delegatevoteschanged":        &joetoken.DelegateVotesChanged{},
	"nakji.traderjoe.0_0_0.joetoken_ownershiptransferred":        &joetoken.OwnershipTransferred{},
	"nakji.traderjoe.0_0_0.joetoken_transfer":                    &joetoken.Transfer{},
	"nakji.traderjoe.0_0_0.joetroller_failure":                   &joetroller.Failure{},
	"nakji.traderjoe.0_0_0.joetroller_newadmin":                  &joetroller.NewAdmin{},
	"nakji.traderjoe.0_0_0.joetroller_newimplementation":         &joetroller.NewImplementation{},
	"nakji.traderjoe.0_0_0.joetroller_newpendingadmin":           &joetroller.NewPendingAdmin{},
	"nakji.traderjoe.0_0_0.joetroller_newpendingimplementation":  &joetroller.NewPendingImplementation{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_add":                  &masterchefjoev2.Add{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_deposit":              &masterchefjoev2.Deposit{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_emergencywithdraw":    &masterchefjoev2.EmergencyWithdraw{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_harvest":              &masterchefjoev2.Harvest{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_ownershiptransferred": &masterchefjoev2.OwnershipTransferred{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_set":                  &masterchefjoev2.Set{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_setdevaddress":        &masterchefjoev2.SetDevAddress{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_updateemissionrate":   &masterchefjoev2.UpdateEmissionRate{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_updatepool":           &masterchefjoev2.UpdatePool{},
	"nakji.traderjoe.0_0_0.masterchefjoev2_withdraw":             &masterchefjoev2.Withdraw{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_add":                  &masterchefjoev3.Add{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_deposit":              &masterchefjoev3.Deposit{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_emergencywithdraw":    &masterchefjoev3.EmergencyWithdraw{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_harvest":              &masterchefjoev3.Harvest{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_init":                 &masterchefjoev3.Init{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_ownershiptransferred": &masterchefjoev3.OwnershipTransferred{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_set":                  &masterchefjoev3.Set{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_updatepool":           &masterchefjoev3.UpdatePool{},
	"nakji.traderjoe.0_0_0.masterchefjoev3_withdraw":             &masterchefjoev3.Withdraw{},
}
