// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: connectors/source/aave/lendingpool/lendingpool.gen.proto

package lendingpool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LendingPoolBorrow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block      uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx        uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx         []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`                 // tx hash
	Reserve    []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"`       // address
	User       []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`             // address
	BehalfOf   []byte                 `protobuf:"bytes,7,opt,name=behalfOf,proto3" json:"behalfOf,omitempty"`     // address
	Amount     []byte                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`         // uint256
	BorrowRate []byte                 `protobuf:"bytes,9,opt,name=borrowRate,proto3" json:"borrowRate,omitempty"` // uint256
	RateMode   []byte                 `protobuf:"bytes,10,opt,name=rateMode,proto3" json:"rateMode,omitempty"`    // uint256
	Referral   uint64                 `protobuf:"varint,11,opt,name=referral,proto3" json:"referral,omitempty"`   // uint16
	Ns         string                 `protobuf:"bytes,12,opt,name=ns,proto3" json:"ns,omitempty"`
	S          string                 `protobuf:"bytes,13,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolBorrow) Reset() {
	*x = LendingPoolBorrow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolBorrow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolBorrow) ProtoMessage() {}

func (x *LendingPoolBorrow) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolBorrow.ProtoReflect.Descriptor instead.
func (*LendingPoolBorrow) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{0}
}

func (x *LendingPoolBorrow) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolBorrow) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolBorrow) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolBorrow) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolBorrow) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolBorrow) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolBorrow) GetBehalfOf() []byte {
	if x != nil {
		return x.BehalfOf
	}
	return nil
}

func (x *LendingPoolBorrow) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LendingPoolBorrow) GetBorrowRate() []byte {
	if x != nil {
		return x.BorrowRate
	}
	return nil
}

func (x *LendingPoolBorrow) GetRateMode() []byte {
	if x != nil {
		return x.RateMode
	}
	return nil
}

func (x *LendingPoolBorrow) GetReferral() uint64 {
	if x != nil {
		return x.Referral
	}
	return 0
}

func (x *LendingPoolBorrow) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolBorrow) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block    uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx      uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx       []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`              // tx hash
	Reserve  []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"`    // address
	User     []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`          // address
	BehalfOf []byte                 `protobuf:"bytes,7,opt,name=behalfOf,proto3" json:"behalfOf,omitempty"`  // address
	Amount   []byte                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`      // uint256
	Referral uint64                 `protobuf:"varint,9,opt,name=referral,proto3" json:"referral,omitempty"` // uint16
	Ns       string                 `protobuf:"bytes,10,opt,name=ns,proto3" json:"ns,omitempty"`
	S        string                 `protobuf:"bytes,11,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolDeposit) Reset() {
	*x = LendingPoolDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolDeposit) ProtoMessage() {}

func (x *LendingPoolDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolDeposit.ProtoReflect.Descriptor instead.
func (*LendingPoolDeposit) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{1}
}

func (x *LendingPoolDeposit) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolDeposit) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolDeposit) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolDeposit) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolDeposit) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolDeposit) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolDeposit) GetBehalfOf() []byte {
	if x != nil {
		return x.BehalfOf
	}
	return nil
}

func (x *LendingPoolDeposit) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LendingPoolDeposit) GetReferral() uint64 {
	if x != nil {
		return x.Referral
	}
	return 0
}

func (x *LendingPoolDeposit) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolDeposit) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolFlashLoan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block     uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx       uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx        []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`               // tx hash
	Target    []byte                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`       // address
	Initiator []byte                 `protobuf:"bytes,6,opt,name=initiator,proto3" json:"initiator,omitempty"` // address
	Asset     []byte                 `protobuf:"bytes,7,opt,name=asset,proto3" json:"asset,omitempty"`         // address
	Amount    []byte                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`       // uint256
	Premium   []byte                 `protobuf:"bytes,9,opt,name=premium,proto3" json:"premium,omitempty"`     // uint256
	Referral  uint64                 `protobuf:"varint,10,opt,name=referral,proto3" json:"referral,omitempty"` // uint16
	Ns        string                 `protobuf:"bytes,11,opt,name=ns,proto3" json:"ns,omitempty"`
	S         string                 `protobuf:"bytes,12,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolFlashLoan) Reset() {
	*x = LendingPoolFlashLoan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolFlashLoan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolFlashLoan) ProtoMessage() {}

func (x *LendingPoolFlashLoan) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolFlashLoan.ProtoReflect.Descriptor instead.
func (*LendingPoolFlashLoan) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{2}
}

func (x *LendingPoolFlashLoan) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolFlashLoan) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolFlashLoan) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetInitiator() []byte {
	if x != nil {
		return x.Initiator
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetAsset() []byte {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetPremium() []byte {
	if x != nil {
		return x.Premium
	}
	return nil
}

func (x *LendingPoolFlashLoan) GetReferral() uint64 {
	if x != nil {
		return x.Referral
	}
	return 0
}

func (x *LendingPoolFlashLoan) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolFlashLoan) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolLiquidationCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts               *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block            uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx              uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx               []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`                             // tx hash
	CollateralAsset  []byte                 `protobuf:"bytes,5,opt,name=collateralAsset,proto3" json:"collateralAsset,omitempty"`   // address
	DebtAsset        []byte                 `protobuf:"bytes,6,opt,name=debtAsset,proto3" json:"debtAsset,omitempty"`               // address
	User             []byte                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`                         // address
	DebtToCover      []byte                 `protobuf:"bytes,8,opt,name=debtToCover,proto3" json:"debtToCover,omitempty"`           // uint256
	CollateralAmount []byte                 `protobuf:"bytes,9,opt,name=collateralAmount,proto3" json:"collateralAmount,omitempty"` // uint256
	Liquidator       []byte                 `protobuf:"bytes,10,opt,name=liquidator,proto3" json:"liquidator,omitempty"`            // address
	ReceiveAToken    bool                   `protobuf:"varint,11,opt,name=receiveAToken,proto3" json:"receiveAToken,omitempty"`
	Ns               string                 `protobuf:"bytes,12,opt,name=ns,proto3" json:"ns,omitempty"`
	S                string                 `protobuf:"bytes,13,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolLiquidationCall) Reset() {
	*x = LendingPoolLiquidationCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolLiquidationCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolLiquidationCall) ProtoMessage() {}

func (x *LendingPoolLiquidationCall) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolLiquidationCall.ProtoReflect.Descriptor instead.
func (*LendingPoolLiquidationCall) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{3}
}

func (x *LendingPoolLiquidationCall) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolLiquidationCall) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolLiquidationCall) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetCollateralAsset() []byte {
	if x != nil {
		return x.CollateralAsset
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetDebtAsset() []byte {
	if x != nil {
		return x.DebtAsset
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetDebtToCover() []byte {
	if x != nil {
		return x.DebtToCover
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetCollateralAmount() []byte {
	if x != nil {
		return x.CollateralAmount
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetLiquidator() []byte {
	if x != nil {
		return x.Liquidator
	}
	return nil
}

func (x *LendingPoolLiquidationCall) GetReceiveAToken() bool {
	if x != nil {
		return x.ReceiveAToken
	}
	return false
}

func (x *LendingPoolLiquidationCall) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolLiquidationCall) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolRebalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block   uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx     uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx      []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`           // tx hash
	Reserve []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"` // address
	User    []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`       // address
	Ns      string                 `protobuf:"bytes,7,opt,name=ns,proto3" json:"ns,omitempty"`
	S       string                 `protobuf:"bytes,8,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolRebalance) Reset() {
	*x = LendingPoolRebalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolRebalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolRebalance) ProtoMessage() {}

func (x *LendingPoolRebalance) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolRebalance.ProtoReflect.Descriptor instead.
func (*LendingPoolRebalance) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{4}
}

func (x *LendingPoolRebalance) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolRebalance) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolRebalance) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolRebalance) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolRebalance) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolRebalance) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolRebalance) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolRebalance) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolRepay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block   uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx     uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx      []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`           // tx hash
	Reserve []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"` // address
	User    []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`       // address
	Amount  []byte                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`   // uint256
	Repayer []byte                 `protobuf:"bytes,8,opt,name=repayer,proto3" json:"repayer,omitempty"` //address
	Ns      string                 `protobuf:"bytes,9,opt,name=ns,proto3" json:"ns,omitempty"`
	S       string                 `protobuf:"bytes,10,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolRepay) Reset() {
	*x = LendingPoolRepay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolRepay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolRepay) ProtoMessage() {}

func (x *LendingPoolRepay) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolRepay.ProtoReflect.Descriptor instead.
func (*LendingPoolRepay) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{5}
}

func (x *LendingPoolRepay) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolRepay) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolRepay) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolRepay) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolRepay) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolRepay) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolRepay) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LendingPoolRepay) GetRepayer() []byte {
	if x != nil {
		return x.Repayer
	}
	return nil
}

func (x *LendingPoolRepay) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolRepay) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolReserveAsCollateral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block      uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx        uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx         []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`           // tx hash
	Reserve    []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"` // address
	User       []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`       // address
	Collateral bool                   `protobuf:"varint,7,opt,name=collateral,proto3" json:"collateral,omitempty"`
	Ns         string                 `protobuf:"bytes,8,opt,name=ns,proto3" json:"ns,omitempty"`
	S          string                 `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolReserveAsCollateral) Reset() {
	*x = LendingPoolReserveAsCollateral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolReserveAsCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolReserveAsCollateral) ProtoMessage() {}

func (x *LendingPoolReserveAsCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolReserveAsCollateral.ProtoReflect.Descriptor instead.
func (*LendingPoolReserveAsCollateral) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{6}
}

func (x *LendingPoolReserveAsCollateral) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolReserveAsCollateral) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolReserveAsCollateral) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolReserveAsCollateral) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolReserveAsCollateral) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolReserveAsCollateral) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolReserveAsCollateral) GetCollateral() bool {
	if x != nil {
		return x.Collateral
	}
	return false
}

func (x *LendingPoolReserveAsCollateral) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolReserveAsCollateral) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolReserveUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts               *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block            uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx              uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx               []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`                             // tx hash
	Reserve          []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"`                   // address
	LiquidityRate    []byte                 `protobuf:"bytes,6,opt,name=liquidityRate,proto3" json:"liquidityRate,omitempty"`       // uint256
	StableBorrowRate []byte                 `protobuf:"bytes,7,opt,name=stableBorrowRate,proto3" json:"stableBorrowRate,omitempty"` // uint256
	VarBorrowRate    []byte                 `protobuf:"bytes,8,opt,name=varBorrowRate,proto3" json:"varBorrowRate,omitempty"`       // uint256
	LiquidityIndex   []byte                 `protobuf:"bytes,9,opt,name=liquidityIndex,proto3" json:"liquidityIndex,omitempty"`     // uint256
	VarBorrowIndex   []byte                 `protobuf:"bytes,10,opt,name=varBorrowIndex,proto3" json:"varBorrowIndex,omitempty"`    // uint256
	Ns               string                 `protobuf:"bytes,11,opt,name=ns,proto3" json:"ns,omitempty"`
	S                string                 `protobuf:"bytes,12,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolReserveUpdated) Reset() {
	*x = LendingPoolReserveUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolReserveUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolReserveUpdated) ProtoMessage() {}

func (x *LendingPoolReserveUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolReserveUpdated.ProtoReflect.Descriptor instead.
func (*LendingPoolReserveUpdated) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{7}
}

func (x *LendingPoolReserveUpdated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolReserveUpdated) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolReserveUpdated) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetLiquidityRate() []byte {
	if x != nil {
		return x.LiquidityRate
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetStableBorrowRate() []byte {
	if x != nil {
		return x.StableBorrowRate
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetVarBorrowRate() []byte {
	if x != nil {
		return x.VarBorrowRate
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetLiquidityIndex() []byte {
	if x != nil {
		return x.LiquidityIndex
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetVarBorrowIndex() []byte {
	if x != nil {
		return x.VarBorrowIndex
	}
	return nil
}

func (x *LendingPoolReserveUpdated) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolReserveUpdated) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolSwap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block    uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx      uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx       []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`             // tx hash
	Reserve  []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"`   // address
	User     []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`         // address
	RateMode []byte                 `protobuf:"bytes,7,opt,name=rateMode,proto3" json:"rateMode,omitempty"` // uint256
	Ns       string                 `protobuf:"bytes,8,opt,name=ns,proto3" json:"ns,omitempty"`
	S        string                 `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolSwap) Reset() {
	*x = LendingPoolSwap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolSwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolSwap) ProtoMessage() {}

func (x *LendingPoolSwap) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolSwap.ProtoReflect.Descriptor instead.
func (*LendingPoolSwap) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{8}
}

func (x *LendingPoolSwap) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolSwap) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolSwap) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolSwap) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolSwap) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolSwap) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolSwap) GetRateMode() []byte {
	if x != nil {
		return x.RateMode
	}
	return nil
}

func (x *LendingPoolSwap) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolSwap) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type LendingPoolWithdraw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Block   uint64                 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Idx     uint64                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Tx      []byte                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`           // tx hash
	Reserve []byte                 `protobuf:"bytes,5,opt,name=reserve,proto3" json:"reserve,omitempty"` // address
	User    []byte                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`       // address
	Amount  []byte                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`   // uint256
	To      []byte                 `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`           // address
	Ns      string                 `protobuf:"bytes,9,opt,name=ns,proto3" json:"ns,omitempty"`
	S       string                 `protobuf:"bytes,10,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *LendingPoolWithdraw) Reset() {
	*x = LendingPoolWithdraw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPoolWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPoolWithdraw) ProtoMessage() {}

func (x *LendingPoolWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPoolWithdraw.ProtoReflect.Descriptor instead.
func (*LendingPoolWithdraw) Descriptor() ([]byte, []int) {
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP(), []int{9}
}

func (x *LendingPoolWithdraw) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LendingPoolWithdraw) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *LendingPoolWithdraw) GetIdx() uint64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *LendingPoolWithdraw) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *LendingPoolWithdraw) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *LendingPoolWithdraw) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LendingPoolWithdraw) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *LendingPoolWithdraw) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *LendingPoolWithdraw) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *LendingPoolWithdraw) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_connectors_source_aave_lendingpool_lendingpool_gen_proto protoreflect.FileDescriptor

var file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDesc = []byte{
	0x0a, 0x38, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x61, 0x61, 0x76, 0x65, 0x2f, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6f, 0x6c,
	0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6f, 0x6c, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x02, 0x0a, 0x11, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x12, 0x2a,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69,
	0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x68, 0x61, 0x6c, 0x66, 0x4f, 0x66, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x62, 0x65, 0x68, 0x61, 0x6c, 0x66, 0x4f, 0x66, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x61,
	0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x6e, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01,
	0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x94, 0x02, 0x0a, 0x12, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x68, 0x61, 0x6c, 0x66, 0x4f, 0x66, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x65, 0x68, 0x61, 0x6c, 0x66, 0x4f, 0x66, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x73, 0x22, 0xb2, 0x02, 0x0a, 0x14, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f,
	0x6c, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x4c, 0x6f, 0x61, 0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x6d, 0x69, 0x75, 0x6d, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x65, 0x6d, 0x69, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x8e, 0x03, 0x0a, 0x1a, 0x4c, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6c,
	0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x65, 0x62, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x62, 0x74, 0x54, 0x6f, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x64, 0x65, 0x62, 0x74,
	0x54, 0x6f, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x61,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x41, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x14, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73,
	0x22, 0xf4, 0x01, 0x0a, 0x10, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x70, 0x61, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x61, 0x79, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x72, 0x65, 0x70, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xf0, 0x01, 0x0a, 0x1e, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x41, 0x73,
	0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c, 0x0a, 0x01,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xff, 0x02, 0x0a, 0x19, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6c,
	0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x52, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x76, 0x61, 0x72, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x61, 0x74, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x61, 0x72, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x76, 0x61, 0x72, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xdd, 0x01, 0x0a,
	0x0f, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x77, 0x61, 0x70,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xed, 0x01, 0x0a,
	0x13, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x42, 0x2a, 0x5a, 0x28,
	0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x61, 0x61, 0x76, 0x65, 0x2f, 0x6c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescOnce sync.Once
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescData = file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDesc
)

func file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescGZIP() []byte {
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescOnce.Do(func() {
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescData)
	})
	return file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDescData
}

var file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_connectors_source_aave_lendingpool_lendingpool_gen_proto_goTypes = []interface{}{
	(*LendingPoolBorrow)(nil),              // 0: lendingpool.LendingPoolBorrow
	(*LendingPoolDeposit)(nil),             // 1: lendingpool.LendingPoolDeposit
	(*LendingPoolFlashLoan)(nil),           // 2: lendingpool.LendingPoolFlashLoan
	(*LendingPoolLiquidationCall)(nil),     // 3: lendingpool.LendingPoolLiquidationCall
	(*LendingPoolRebalance)(nil),           // 4: lendingpool.LendingPoolRebalance
	(*LendingPoolRepay)(nil),               // 5: lendingpool.LendingPoolRepay
	(*LendingPoolReserveAsCollateral)(nil), // 6: lendingpool.LendingPoolReserveAsCollateral
	(*LendingPoolReserveUpdated)(nil),      // 7: lendingpool.LendingPoolReserveUpdated
	(*LendingPoolSwap)(nil),                // 8: lendingpool.LendingPoolSwap
	(*LendingPoolWithdraw)(nil),            // 9: lendingpool.LendingPoolWithdraw
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
}
var file_connectors_source_aave_lendingpool_lendingpool_gen_proto_depIdxs = []int32{
	10, // 0: lendingpool.LendingPoolBorrow.ts:type_name -> google.protobuf.Timestamp
	10, // 1: lendingpool.LendingPoolDeposit.ts:type_name -> google.protobuf.Timestamp
	10, // 2: lendingpool.LendingPoolFlashLoan.ts:type_name -> google.protobuf.Timestamp
	10, // 3: lendingpool.LendingPoolLiquidationCall.ts:type_name -> google.protobuf.Timestamp
	10, // 4: lendingpool.LendingPoolRebalance.ts:type_name -> google.protobuf.Timestamp
	10, // 5: lendingpool.LendingPoolRepay.ts:type_name -> google.protobuf.Timestamp
	10, // 6: lendingpool.LendingPoolReserveAsCollateral.ts:type_name -> google.protobuf.Timestamp
	10, // 7: lendingpool.LendingPoolReserveUpdated.ts:type_name -> google.protobuf.Timestamp
	10, // 8: lendingpool.LendingPoolSwap.ts:type_name -> google.protobuf.Timestamp
	10, // 9: lendingpool.LendingPoolWithdraw.ts:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_connectors_source_aave_lendingpool_lendingpool_gen_proto_init() }
func file_connectors_source_aave_lendingpool_lendingpool_gen_proto_init() {
	if File_connectors_source_aave_lendingpool_lendingpool_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolBorrow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolFlashLoan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolLiquidationCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolRebalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolRepay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolReserveAsCollateral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolReserveUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolSwap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPoolWithdraw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_aave_lendingpool_lendingpool_gen_proto_goTypes,
		DependencyIndexes: file_connectors_source_aave_lendingpool_lendingpool_gen_proto_depIdxs,
		MessageInfos:      file_connectors_source_aave_lendingpool_lendingpool_gen_proto_msgTypes,
	}.Build()
	File_connectors_source_aave_lendingpool_lendingpool_gen_proto = out.File
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_rawDesc = nil
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_goTypes = nil
	file_connectors_source_aave_lendingpool_lendingpool_gen_proto_depIdxs = nil
}
