// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: connectors/source/starkex/starkex.proto

package starkex

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Asset              string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	AssetType          string                 `protobuf:"bytes,3,opt,name=assetType,proto3" json:"assetType,omitempty"`
	Amount             string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CachedFundingIndex int64                  `protobuf:"varint,5,opt,name=cachedFundingIndex,proto3" json:"cachedFundingIndex,omitempty"`
	VaultKey           string                 `protobuf:"bytes,6,opt,name=vaultKey,proto3" json:"vaultKey,omitempty"`
	BlockNumber        uint64                 `protobuf:"varint,7,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_starkex_starkex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_starkex_starkex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_connectors_source_starkex_starkex_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Position) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Position) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Position) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Position) GetCachedFundingIndex() int64 {
	if x != nil {
		return x.CachedFundingIndex
	}
	return 0
}

func (x *Position) GetVaultKey() string {
	if x != nil {
		return x.VaultKey
	}
	return ""
}

func (x *Position) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

var File_connectors_source_starkex_starkex_proto protoreflect.FileDescriptor

var file_connectors_source_starkex_starkex_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x65, 0x78, 0x2f, 0x73, 0x74, 0x61, 0x72,
	0x6b, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61, 0x72, 0x6b,
	0x65, 0x78, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x28, 0x5a, 0x26, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61,
	0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x65, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_starkex_starkex_proto_rawDescOnce sync.Once
	file_connectors_source_starkex_starkex_proto_rawDescData = file_connectors_source_starkex_starkex_proto_rawDesc
)

func file_connectors_source_starkex_starkex_proto_rawDescGZIP() []byte {
	file_connectors_source_starkex_starkex_proto_rawDescOnce.Do(func() {
		file_connectors_source_starkex_starkex_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_starkex_starkex_proto_rawDescData)
	})
	return file_connectors_source_starkex_starkex_proto_rawDescData
}

var file_connectors_source_starkex_starkex_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connectors_source_starkex_starkex_proto_goTypes = []interface{}{
	(*Position)(nil),              // 0: starkex.Position
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_connectors_source_starkex_starkex_proto_depIdxs = []int32{
	1, // 0: starkex.Position.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connectors_source_starkex_starkex_proto_init() }
func file_connectors_source_starkex_starkex_proto_init() {
	if File_connectors_source_starkex_starkex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_starkex_starkex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_starkex_starkex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_starkex_starkex_proto_goTypes,
		DependencyIndexes: file_connectors_source_starkex_starkex_proto_depIdxs,
		MessageInfos:      file_connectors_source_starkex_starkex_proto_msgTypes,
	}.Build()
	File_connectors_source_starkex_starkex_proto = out.File
	file_connectors_source_starkex_starkex_proto_rawDesc = nil
	file_connectors_source_starkex_starkex_proto_goTypes = nil
	file_connectors_source_starkex_starkex_proto_depIdxs = nil
}
