// Code generated - DO NOT EDIT.
// This file is a generated protobuf definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: connectors/source/axieronin/clockauction/clockauction.gen.proto

package clockauction

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuctionCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seller             []byte                 `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	ListingIndex       []byte                 `protobuf:"bytes,3,opt,name=listingIndex,proto3" json:"listingIndex,omitempty"`     // uint256
	StartingPrices     [][]byte               `protobuf:"bytes,4,rep,name=startingPrices,proto3" json:"startingPrices,omitempty"` // uint256
	EndingPrices       [][]byte               `protobuf:"bytes,5,rep,name=endingPrices,proto3" json:"endingPrices,omitempty"`     // uint256
	ExchangeTokens     [][]byte               `protobuf:"bytes,6,rep,name=exchangeTokens,proto3" json:"exchangeTokens,omitempty"`
	Durations          [][]byte               `protobuf:"bytes,7,rep,name=durations,proto3" json:"durations,omitempty"`                   // uint256
	StartingTimestamps []byte                 `protobuf:"bytes,8,opt,name=startingTimestamps,proto3" json:"startingTimestamps,omitempty"` // uint256
}

func (x *AuctionCreated) Reset() {
	*x = AuctionCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuctionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionCreated) ProtoMessage() {}

func (x *AuctionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionCreated.ProtoReflect.Descriptor instead.
func (*AuctionCreated) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionCreated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AuctionCreated) GetSeller() []byte {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *AuctionCreated) GetListingIndex() []byte {
	if x != nil {
		return x.ListingIndex
	}
	return nil
}

func (x *AuctionCreated) GetStartingPrices() [][]byte {
	if x != nil {
		return x.StartingPrices
	}
	return nil
}

func (x *AuctionCreated) GetEndingPrices() [][]byte {
	if x != nil {
		return x.EndingPrices
	}
	return nil
}

func (x *AuctionCreated) GetExchangeTokens() [][]byte {
	if x != nil {
		return x.ExchangeTokens
	}
	return nil
}

func (x *AuctionCreated) GetDurations() [][]byte {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *AuctionCreated) GetStartingTimestamps() []byte {
	if x != nil {
		return x.StartingTimestamps
	}
	return nil
}

type AuctionSuccessful struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seller       []byte                 `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	Buyer        []byte                 `protobuf:"bytes,3,opt,name=buyer,proto3" json:"buyer,omitempty"`
	ListingIndex []byte                 `protobuf:"bytes,4,opt,name=listingIndex,proto3" json:"listingIndex,omitempty"` // uint256
	Token        []byte                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	TotalPrice   []byte                 `protobuf:"bytes,6,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"` // uint256
}

func (x *AuctionSuccessful) Reset() {
	*x = AuctionSuccessful{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuctionSuccessful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSuccessful) ProtoMessage() {}

func (x *AuctionSuccessful) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSuccessful.ProtoReflect.Descriptor instead.
func (*AuctionSuccessful) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionSuccessful) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AuctionSuccessful) GetSeller() []byte {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *AuctionSuccessful) GetBuyer() []byte {
	if x != nil {
		return x.Buyer
	}
	return nil
}

func (x *AuctionSuccessful) GetListingIndex() []byte {
	if x != nil {
		return x.ListingIndex
	}
	return nil
}

func (x *AuctionSuccessful) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *AuctionSuccessful) GetTotalPrice() []byte {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

type Paused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Paused) Reset() {
	*x = Paused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paused) ProtoMessage() {}

func (x *Paused) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paused.ProtoReflect.Descriptor instead.
func (*Paused) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{2}
}

func (x *Paused) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type TokenAuctionCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seller         []byte                 `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	ListingIndex   []byte                 `protobuf:"bytes,3,opt,name=listingIndex,proto3" json:"listingIndex,omitempty"` // uint256
	ExchangeTokens []byte                 `protobuf:"bytes,4,opt,name=exchangeTokens,proto3" json:"exchangeTokens,omitempty"`
}

func (x *TokenAuctionCancelled) Reset() {
	*x = TokenAuctionCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuctionCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuctionCancelled) ProtoMessage() {}

func (x *TokenAuctionCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuctionCancelled.ProtoReflect.Descriptor instead.
func (*TokenAuctionCancelled) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{3}
}

func (x *TokenAuctionCancelled) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TokenAuctionCancelled) GetSeller() []byte {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *TokenAuctionCancelled) GetListingIndex() []byte {
	if x != nil {
		return x.ListingIndex
	}
	return nil
}

func (x *TokenAuctionCancelled) GetExchangeTokens() []byte {
	if x != nil {
		return x.ExchangeTokens
	}
	return nil
}

type Unpaused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Unpaused) Reset() {
	*x = Unpaused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unpaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unpaused) ProtoMessage() {}

func (x *Unpaused) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unpaused.ProtoReflect.Descriptor instead.
func (*Unpaused) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{4}
}

func (x *Unpaused) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type AdminChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldAdmin []byte                 `protobuf:"bytes,2,opt,name=oldAdmin,proto3" json:"oldAdmin,omitempty"`
	NewAdmin []byte                 `protobuf:"bytes,3,opt,name=newAdmin,proto3" json:"newAdmin,omitempty"`
}

func (x *AdminChanged) Reset() {
	*x = AdminChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminChanged) ProtoMessage() {}

func (x *AdminChanged) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminChanged.ProtoReflect.Descriptor instead.
func (*AdminChanged) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{5}
}

func (x *AdminChanged) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AdminChanged) GetOldAdmin() []byte {
	if x != nil {
		return x.OldAdmin
	}
	return nil
}

func (x *AdminChanged) GetNewAdmin() []byte {
	if x != nil {
		return x.NewAdmin
	}
	return nil
}

type AdminRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldAdmin []byte                 `protobuf:"bytes,2,opt,name=oldAdmin,proto3" json:"oldAdmin,omitempty"`
}

func (x *AdminRemoved) Reset() {
	*x = AdminRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRemoved) ProtoMessage() {}

func (x *AdminRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRemoved.ProtoReflect.Descriptor instead.
func (*AdminRemoved) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{6}
}

func (x *AdminRemoved) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AdminRemoved) GetOldAdmin() []byte {
	if x != nil {
		return x.OldAdmin
	}
	return nil
}

type AuctionCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seller       []byte                 `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	ListingIndex []byte                 `protobuf:"bytes,3,opt,name=listingIndex,proto3" json:"listingIndex,omitempty"` // uint256
}

func (x *AuctionCancelled) Reset() {
	*x = AuctionCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuctionCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionCancelled) ProtoMessage() {}

func (x *AuctionCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionCancelled.ProtoReflect.Descriptor instead.
func (*AuctionCancelled) Descriptor() ([]byte, []int) {
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP(), []int{7}
}

func (x *AuctionCancelled) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AuctionCancelled) GetSeller() []byte {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *AuctionCancelled) GetListingIndex() []byte {
	if x != nil {
		return x.ListingIndex
	}
	return nil
}

var File_connectors_source_axieronin_clockauction_clockauction_gen_proto protoreflect.FileDescriptor

var file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x61, 0x78, 0x69, 0x65, 0x72, 0x6f, 0x6e, 0x69, 0x6e, 0x2f, 0x63, 0x6c,
	0x6f, 0x63, 0x6b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xba, 0x02, 0x0a, 0x0e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x09, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x0a,
	0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x22, 0xc7, 0x01,
	0x0a, 0x11, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x79, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x75, 0x79, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x50, 0x61, 0x75, 0x73, 0x65,
	0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0xa7, 0x01,
	0x0a, 0x15, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x02, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x26, 0x0a, 0x0e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x36, 0x0a, 0x08, 0x55, 0x6e, 0x70, 0x61, 0x75,
	0x73, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22,
	0x72, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f,
	0x6c, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f,
	0x6c, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x22, 0x56, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x7a, 0x0a, 0x10, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x26, 0x5a, 0x24, 0x62, 0x6c, 0x65, 0x70, 0x2e,
	0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescOnce sync.Once
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescData = file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDesc
)

func file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescGZIP() []byte {
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescOnce.Do(func() {
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescData)
	})
	return file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDescData
}

var file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_connectors_source_axieronin_clockauction_clockauction_gen_proto_goTypes = []interface{}{
	(*AuctionCreated)(nil),        // 0: clockauction.AuctionCreated
	(*AuctionSuccessful)(nil),     // 1: clockauction.AuctionSuccessful
	(*Paused)(nil),                // 2: clockauction.Paused
	(*TokenAuctionCancelled)(nil), // 3: clockauction.TokenAuctionCancelled
	(*Unpaused)(nil),              // 4: clockauction.Unpaused
	(*AdminChanged)(nil),          // 5: clockauction.AdminChanged
	(*AdminRemoved)(nil),          // 6: clockauction.AdminRemoved
	(*AuctionCancelled)(nil),      // 7: clockauction.AuctionCancelled
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_connectors_source_axieronin_clockauction_clockauction_gen_proto_depIdxs = []int32{
	8, // 0: clockauction.AuctionCreated.ts:type_name -> google.protobuf.Timestamp
	8, // 1: clockauction.AuctionSuccessful.ts:type_name -> google.protobuf.Timestamp
	8, // 2: clockauction.Paused.ts:type_name -> google.protobuf.Timestamp
	8, // 3: clockauction.TokenAuctionCancelled.ts:type_name -> google.protobuf.Timestamp
	8, // 4: clockauction.Unpaused.ts:type_name -> google.protobuf.Timestamp
	8, // 5: clockauction.AdminChanged.ts:type_name -> google.protobuf.Timestamp
	8, // 6: clockauction.AdminRemoved.ts:type_name -> google.protobuf.Timestamp
	8, // 7: clockauction.AuctionCancelled.ts:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_connectors_source_axieronin_clockauction_clockauction_gen_proto_init() }
func file_connectors_source_axieronin_clockauction_clockauction_gen_proto_init() {
	if File_connectors_source_axieronin_clockauction_clockauction_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuctionCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuctionSuccessful); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenAuctionCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unpaused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuctionCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_axieronin_clockauction_clockauction_gen_proto_goTypes,
		DependencyIndexes: file_connectors_source_axieronin_clockauction_clockauction_gen_proto_depIdxs,
		MessageInfos:      file_connectors_source_axieronin_clockauction_clockauction_gen_proto_msgTypes,
	}.Build()
	File_connectors_source_axieronin_clockauction_clockauction_gen_proto = out.File
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_rawDesc = nil
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_goTypes = nil
	file_connectors_source_axieronin_clockauction_clockauction_gen_proto_depIdxs = nil
}
