// Code generated - DO NOT EDIT.
// This file is a generated protobuf definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.19.4
// source: connectors/source/axie/slp/slp.gen.proto

package slp

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MinterAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Minter []byte                 `protobuf:"bytes,2,opt,name=minter,proto3" json:"minter,omitempty"`
}

func (x *MinterAdded) Reset() {
	*x = MinterAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinterAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinterAdded) ProtoMessage() {}

func (x *MinterAdded) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinterAdded.ProtoReflect.Descriptor instead.
func (*MinterAdded) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{0}
}

func (x *MinterAdded) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *MinterAdded) GetMinter() []byte {
	if x != nil {
		return x.Minter
	}
	return nil
}

type MinterRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Minter []byte                 `protobuf:"bytes,2,opt,name=minter,proto3" json:"minter,omitempty"`
}

func (x *MinterRemoved) Reset() {
	*x = MinterRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinterRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinterRemoved) ProtoMessage() {}

func (x *MinterRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinterRemoved.ProtoReflect.Descriptor instead.
func (*MinterRemoved) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{1}
}

func (x *MinterRemoved) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *MinterRemoved) GetMinter() []byte {
	if x != nil {
		return x.Minter
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	From  []byte                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To    []byte                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // uint256
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{2}
}

func (x *Transfer) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Transfer) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transfer) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transfer) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type AdminChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldAdmin []byte                 `protobuf:"bytes,2,opt,name=oldAdmin,proto3" json:"oldAdmin,omitempty"`
	NewAdmin []byte                 `protobuf:"bytes,3,opt,name=newAdmin,proto3" json:"newAdmin,omitempty"`
}

func (x *AdminChanged) Reset() {
	*x = AdminChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminChanged) ProtoMessage() {}

func (x *AdminChanged) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminChanged.ProtoReflect.Descriptor instead.
func (*AdminChanged) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{3}
}

func (x *AdminChanged) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AdminChanged) GetOldAdmin() []byte {
	if x != nil {
		return x.OldAdmin
	}
	return nil
}

func (x *AdminChanged) GetNewAdmin() []byte {
	if x != nil {
		return x.NewAdmin
	}
	return nil
}

type AdminRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldAdmin []byte                 `protobuf:"bytes,2,opt,name=oldAdmin,proto3" json:"oldAdmin,omitempty"`
}

func (x *AdminRemoved) Reset() {
	*x = AdminRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRemoved) ProtoMessage() {}

func (x *AdminRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRemoved.ProtoReflect.Descriptor instead.
func (*AdminRemoved) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{4}
}

func (x *AdminRemoved) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AdminRemoved) GetOldAdmin() []byte {
	if x != nil {
		return x.OldAdmin
	}
	return nil
}

type Approval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Owner   []byte                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender []byte                 `protobuf:"bytes,3,opt,name=spender,proto3" json:"spender,omitempty"`
	Value   []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // uint256
}

func (x *Approval) Reset() {
	*x = Approval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_axie_slp_slp_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP(), []int{5}
}

func (x *Approval) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Approval) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Approval) GetSpender() []byte {
	if x != nil {
		return x.Spender
	}
	return nil
}

func (x *Approval) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_connectors_source_axie_slp_slp_gen_proto protoreflect.FileDescriptor

var file_connectors_source_axie_slp_slp_gen_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x61, 0x78, 0x69, 0x65, 0x2f, 0x73, 0x6c, 0x70, 0x2f, 0x73, 0x6c, 0x70,
	0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x6c, 0x70, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x51, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x70, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x72, 0x0a, 0x0c, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x56,
	0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x2a,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x6c,
	0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f, 0x6c,
	0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x7c, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f,
	0x73, 0x6c, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_axie_slp_slp_gen_proto_rawDescOnce sync.Once
	file_connectors_source_axie_slp_slp_gen_proto_rawDescData = file_connectors_source_axie_slp_slp_gen_proto_rawDesc
)

func file_connectors_source_axie_slp_slp_gen_proto_rawDescGZIP() []byte {
	file_connectors_source_axie_slp_slp_gen_proto_rawDescOnce.Do(func() {
		file_connectors_source_axie_slp_slp_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_axie_slp_slp_gen_proto_rawDescData)
	})
	return file_connectors_source_axie_slp_slp_gen_proto_rawDescData
}

var file_connectors_source_axie_slp_slp_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_connectors_source_axie_slp_slp_gen_proto_goTypes = []interface{}{
	(*MinterAdded)(nil),           // 0: slp.MinterAdded
	(*MinterRemoved)(nil),         // 1: slp.MinterRemoved
	(*Transfer)(nil),              // 2: slp.Transfer
	(*AdminChanged)(nil),          // 3: slp.AdminChanged
	(*AdminRemoved)(nil),          // 4: slp.AdminRemoved
	(*Approval)(nil),              // 5: slp.Approval
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_connectors_source_axie_slp_slp_gen_proto_depIdxs = []int32{
	6, // 0: slp.MinterAdded.ts:type_name -> google.protobuf.Timestamp
	6, // 1: slp.MinterRemoved.ts:type_name -> google.protobuf.Timestamp
	6, // 2: slp.Transfer.ts:type_name -> google.protobuf.Timestamp
	6, // 3: slp.AdminChanged.ts:type_name -> google.protobuf.Timestamp
	6, // 4: slp.AdminRemoved.ts:type_name -> google.protobuf.Timestamp
	6, // 5: slp.Approval.ts:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_connectors_source_axie_slp_slp_gen_proto_init() }
func file_connectors_source_axie_slp_slp_gen_proto_init() {
	if File_connectors_source_axie_slp_slp_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinterAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinterRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connectors_source_axie_slp_slp_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_axie_slp_slp_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_axie_slp_slp_gen_proto_goTypes,
		DependencyIndexes: file_connectors_source_axie_slp_slp_gen_proto_depIdxs,
		MessageInfos:      file_connectors_source_axie_slp_slp_gen_proto_msgTypes,
	}.Build()
	File_connectors_source_axie_slp_slp_gen_proto = out.File
	file_connectors_source_axie_slp_slp_gen_proto_rawDesc = nil
	file_connectors_source_axie_slp_slp_gen_proto_goTypes = nil
	file_connectors_source_axie_slp_slp_gen_proto_depIdxs = nil
}
