// Code generated by connectorgen - Edit as necessary.
package eth2

import (
	"blep.ai/data/connectors/source/eth2/eth2"
	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]proto.Message{
	"nakji.eth2.0_0_0.eth2_depositevent": &eth2.DepositEvent{},
	"nakji.eth2.0_0_0.eth2.depositcount": &eth2.DepositCount{},
}
