// Code generated by connectorgen - Edit as necessary.
package chi

import (
	"blep.ai/data/connectors/source/chi/chi"
	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]proto.Message{
	"nakji.chi.0_0_0.chi_approval": &chi.Approval{},
	"nakji.chi.0_0_0.chi_transfer": &chi.Transfer{},
}
