// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: connectors/source/uniswapv2/pair.proto

package uniswapv2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ns     string                 `protobuf:"bytes,2,opt,name=ns,proto3" json:"ns,omitempty"`
	Id     []byte                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Added  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=added,proto3" json:"added,omitempty"`
	App    string                 `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	I      int64                  `protobuf:"varint,5,opt,name=i,proto3" json:"i,omitempty"`
	Token0 []byte                 `protobuf:"bytes,6,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1 []byte                 `protobuf:"bytes,7,opt,name=token1,proto3" json:"token1,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connectors_source_uniswapv2_pair_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_source_uniswapv2_pair_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_connectors_source_uniswapv2_pair_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Pair) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Pair) GetAdded() *timestamppb.Timestamp {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *Pair) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Pair) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Pair) GetToken0() []byte {
	if x != nil {
		return x.Token0
	}
	return nil
}

func (x *Pair) GetToken1() []byte {
	if x != nil {
		return x.Token1
	}
	return nil
}

var File_connectors_source_uniswapv2_pair_proto protoreflect.FileDescriptor

var file_connectors_source_uniswapv2_pair_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x75, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x76, 0x32, 0x2f, 0x70, 0x61,
	0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x75, 0x6e, 0x69, 0x73, 0x77, 0x61,
	0x70, 0x76, 0x32, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a,
	0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70,
	0x70, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x69, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x42,
	0x2a, 0x5a, 0x28, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2f, 0x75, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_connectors_source_uniswapv2_pair_proto_rawDescOnce sync.Once
	file_connectors_source_uniswapv2_pair_proto_rawDescData = file_connectors_source_uniswapv2_pair_proto_rawDesc
)

func file_connectors_source_uniswapv2_pair_proto_rawDescGZIP() []byte {
	file_connectors_source_uniswapv2_pair_proto_rawDescOnce.Do(func() {
		file_connectors_source_uniswapv2_pair_proto_rawDescData = protoimpl.X.CompressGZIP(file_connectors_source_uniswapv2_pair_proto_rawDescData)
	})
	return file_connectors_source_uniswapv2_pair_proto_rawDescData
}

var file_connectors_source_uniswapv2_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connectors_source_uniswapv2_pair_proto_goTypes = []interface{}{
	(*Pair)(nil),                  // 0: uniswapv2.Pair
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_connectors_source_uniswapv2_pair_proto_depIdxs = []int32{
	1, // 0: uniswapv2.Pair.added:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connectors_source_uniswapv2_pair_proto_init() }
func file_connectors_source_uniswapv2_pair_proto_init() {
	if File_connectors_source_uniswapv2_pair_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connectors_source_uniswapv2_pair_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connectors_source_uniswapv2_pair_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_source_uniswapv2_pair_proto_goTypes,
		DependencyIndexes: file_connectors_source_uniswapv2_pair_proto_depIdxs,
		MessageInfos:      file_connectors_source_uniswapv2_pair_proto_msgTypes,
	}.Build()
	File_connectors_source_uniswapv2_pair_proto = out.File
	file_connectors_source_uniswapv2_pair_proto_rawDesc = nil
	file_connectors_source_uniswapv2_pair_proto_goTypes = nil
	file_connectors_source_uniswapv2_pair_proto_depIdxs = nil
}
