// Code generated by connectorgen - Edit as necessary.
package axieronin

import (
	"blep.ai/data/connectors/source/axie/axienft"
	"blep.ai/data/connectors/source/axie/axs"
	"blep.ai/data/connectors/source/axie/slp"
	"blep.ai/data/connectors/source/axieronin/clockauction"
	"blep.ai/data/connectors/source/axieronin/land"
	"blep.ai/data/connectors/source/axieronin/landitem"
	"blep.ai/data/connectors/source/axieronin/roninweth"
	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]proto.Message{
	"nakji.axieronin.0_0_0.axienft_approval":                   &axienft.Approval{},
	"nakji.axieronin.0_0_0.axienft_approvalforall":             &axienft.ApprovalForAll{},
	"nakji.axieronin.0_0_0.axienft_axieevolved":                &axienft.AxieEvolved{},
	"nakji.axieronin.0_0_0.axienft_axierebirthed":              &axienft.AxieRebirthed{},
	"nakji.axieronin.0_0_0.axienft_axieretired":                &axienft.AxieRetired{},
	"nakji.axieronin.0_0_0.axienft_axiespawned":                &axienft.AxieSpawned{},
	"nakji.axieronin.0_0_0.axienft_transfer":                   &axienft.Transfer{},
	"nakji.axieronin.0_0_0.axs_approval":                       &axs.Approval{},
	"nakji.axieronin.0_0_0.axs_transfer":                       &axs.Transfer{},
	"nakji.axieronin.0_0_0.clockauction_adminchanged":          &clockauction.AdminChanged{},
	"nakji.axieronin.0_0_0.clockauction_adminremoved":          &clockauction.AdminRemoved{},
	"nakji.axieronin.0_0_0.clockauction_auctioncancelled":      &clockauction.AuctionCancelled{},
	"nakji.axieronin.0_0_0.clockauction_auctioncreated":        &clockauction.AuctionCreated{},
	"nakji.axieronin.0_0_0.clockauction_auctionsuccessful":     &clockauction.AuctionSuccessful{},
	"nakji.axieronin.0_0_0.clockauction_paused":                &clockauction.Paused{},
	"nakji.axieronin.0_0_0.clockauction_tokenauctioncancelled": &clockauction.TokenAuctionCancelled{},
	"nakji.axieronin.0_0_0.clockauction_unpaused":              &clockauction.Unpaused{},
	"nakji.axieronin.0_0_0.land_adminchanged":                  &land.AdminChanged{},
	"nakji.axieronin.0_0_0.land_adminremoved":                  &land.AdminRemoved{},
	"nakji.axieronin.0_0_0.land_approval":                      &land.Approval{},
	"nakji.axieronin.0_0_0.land_approvalforall":                &land.ApprovalForAll{},
	"nakji.axieronin.0_0_0.land_minteradded":                   &land.MinterAdded{},
	"nakji.axieronin.0_0_0.land_minterremoved":                 &land.MinterRemoved{},
	"nakji.axieronin.0_0_0.land_nonceupdated":                  &land.NonceUpdated{},
	"nakji.axieronin.0_0_0.land_paused":                        &land.Paused{},
	"nakji.axieronin.0_0_0.land_spenderunwhitelisted":          &land.SpenderUnwhitelisted{},
	"nakji.axieronin.0_0_0.land_spenderwhitelisted":            &land.SpenderWhitelisted{},
	"nakji.axieronin.0_0_0.land_transfer":                      &land.Transfer{},
	"nakji.axieronin.0_0_0.land_unpaused":                      &land.Unpaused{},
	"nakji.axieronin.0_0_0.landitem_adminchanged":              &landitem.AdminChanged{},
	"nakji.axieronin.0_0_0.landitem_adminremoved":              &landitem.AdminRemoved{},
	"nakji.axieronin.0_0_0.landitem_approval":                  &landitem.Approval{},
	"nakji.axieronin.0_0_0.landitem_approvalforall":            &landitem.ApprovalForAll{},
	"nakji.axieronin.0_0_0.landitem_minteradded":               &landitem.MinterAdded{},
	"nakji.axieronin.0_0_0.landitem_minterremoved":             &landitem.MinterRemoved{},
	"nakji.axieronin.0_0_0.landitem_nonceupdated":              &landitem.NonceUpdated{},
	"nakji.axieronin.0_0_0.landitem_paused":                    &landitem.Paused{},
	"nakji.axieronin.0_0_0.landitem_spenderunwhitelisted":      &landitem.SpenderUnwhitelisted{},
	"nakji.axieronin.0_0_0.landitem_spenderwhitelisted":        &landitem.SpenderWhitelisted{},
	"nakji.axieronin.0_0_0.landitem_transfer":                  &landitem.Transfer{},
	"nakji.axieronin.0_0_0.landitem_unpaused":                  &landitem.Unpaused{},
	"nakji.axieronin.0_0_0.roninweth_approval":                 &roninweth.Approval{},
	"nakji.axieronin.0_0_0.roninweth_minteradded":              &roninweth.MinterAdded{},
	"nakji.axieronin.0_0_0.roninweth_minterremoved":            &roninweth.MinterRemoved{},
	"nakji.axieronin.0_0_0.roninweth_transfer":                 &roninweth.Transfer{},
	"nakji.axieronin.0_0_0.slp_adminchanged":                   &slp.AdminChanged{},
	"nakji.axieronin.0_0_0.slp_adminremoved":                   &slp.AdminRemoved{},
	"nakji.axieronin.0_0_0.slp_approval":                       &slp.Approval{},
	"nakji.axieronin.0_0_0.slp_minteradded":                    &slp.MinterAdded{},
	"nakji.axieronin.0_0_0.slp_minterremoved":                  &slp.MinterRemoved{},
	"nakji.axieronin.0_0_0.slp_transfer":                       &slp.Transfer{},
}
